/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.Aluno;
import br.com.controller.Devolucao;
import br.com.controller.Emprestimo;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import br.com.controller.Listas;
import br.com.controller.Livro;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class Tela6_devolucao extends javax.swing.JFrame {
    
    Listas lista = new Listas();
    Date d = new Date();
    String s = new SimpleDateFormat("dd/MM/yyyy").format(d);
    DateTimeFormatter parser = DateTimeFormatter.ofPattern("dd/MM/uuuu");
    LocalDate data = LocalDate.parse(s, parser);
    
    public Tela6_devolucao() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(900, 700);
        
        tabelaRecentes(lista);
        jTPdata.setText("" + data);
        jTPid.setText("" + (lista.getDevolucoes().size() + 1));
        alimentarCB();
        tudoInvisivel();
        tornarGrid();
        
    }
    
    public Tela6_devolucao(Listas lista) {
        initComponents();
        this.lista = lista;
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(900, 700);
        
        tabelaRecentes(lista);
        Date data = new Date();
        String data1 = new SimpleDateFormat("dd/MM/yyyy"). format(data);
        jTPdata.setText(data1);
        jTPid.setText("" + (lista.getDevolucoes().size() + 1));
        alimentarCB();
        tudoInvisivel();
        tornarGrid();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPmenu = new javax.swing.JPanel();
        jBsair = new javax.swing.JButton();
        jTBlistar = new javax.swing.JToggleButton();
        jTBbuscar = new javax.swing.JToggleButton();
        jTBmulta = new javax.swing.JToggleButton();
        jTBremover = new javax.swing.JToggleButton();
        jTBcadastrar = new javax.swing.JToggleButton();
        jBsair1 = new javax.swing.JButton();
        jTBemprestimo = new javax.swing.JToggleButton();
        jPmenuCadastrar = new javax.swing.JPanel();
        jBcadastrarLivro = new javax.swing.JButton();
        jBcadastrarAluno = new javax.swing.JButton();
        jPdevolucao = new javax.swing.JPanel();
        jCBaluno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabelaDevolucao = new javax.swing.JTable();
        jTcodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPid = new javax.swing.JTextPane();
        jCBlivro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPdata = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jBpesquisarCodigo = new javax.swing.JButton();
        jBefetuar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBpesquisarMat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTmatricula = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empréstimo");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPmenu.setBackground(new java.awt.Color(0, 0, 255));
        jPmenu.setPreferredSize(new java.awt.Dimension(1000, 40));

        jBsair.setBackground(new java.awt.Color(0, 0, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/sair.png"))); // NOI18N
        jBsair.setBorder(null);
        jBsair.setContentAreaFilled(false);
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jTBlistar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBlistar.setForeground(new java.awt.Color(255, 255, 255));
        jTBlistar.setText("Listar");
        jTBlistar.setBorder(null);
        jTBlistar.setBorderPainted(false);
        jTBlistar.setContentAreaFilled(false);
        jTBlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBlistar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBlistarActionPerformed(evt);
            }
        });

        jTBbuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTBbuscar.setText("Buscar");
        jTBbuscar.setBorder(null);
        jTBbuscar.setBorderPainted(false);
        jTBbuscar.setContentAreaFilled(false);
        jTBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBbuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBbuscarActionPerformed(evt);
            }
        });

        jTBmulta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBmulta.setForeground(new java.awt.Color(255, 255, 255));
        jTBmulta.setText("Multa");
        jTBmulta.setBorder(null);
        jTBmulta.setBorderPainted(false);
        jTBmulta.setContentAreaFilled(false);
        jTBmulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBmulta.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBmultaActionPerformed(evt);
            }
        });

        jTBremover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBremover.setForeground(new java.awt.Color(255, 255, 255));
        jTBremover.setText("Remover");
        jTBremover.setBorder(null);
        jTBremover.setBorderPainted(false);
        jTBremover.setContentAreaFilled(false);
        jTBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBremover.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBremoverActionPerformed(evt);
            }
        });

        jTBcadastrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jTBcadastrar.setText("Cadastrar");
        jTBcadastrar.setBorder(null);
        jTBcadastrar.setBorderPainted(false);
        jTBcadastrar.setContentAreaFilled(false);
        jTBcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBcadastrar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBcadastrarActionPerformed(evt);
            }
        });

        jBsair1.setBackground(new java.awt.Color(0, 0, 255));
        jBsair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/house.png"))); // NOI18N
        jBsair1.setBorder(null);
        jBsair1.setContentAreaFilled(false);
        jBsair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsair1ActionPerformed(evt);
            }
        });

        jTBemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBemprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jTBemprestimo.setText("Empréstimo");
        jTBemprestimo.setBorder(null);
        jTBemprestimo.setBorderPainted(false);
        jTBemprestimo.setContentAreaFilled(false);
        jTBemprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBemprestimo.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBemprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPmenuLayout = new javax.swing.GroupLayout(jPmenu);
        jPmenu.setLayout(jPmenuLayout);
        jPmenuLayout.setHorizontalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBsair1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTBlistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPmenuLayout.setVerticalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBlistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBsair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPmenu);
        jPmenu.setBounds(0, 0, 1000, 40);

        jPmenuCadastrar.setBackground(new java.awt.Color(51, 51, 255));

        jBcadastrarLivro.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarLivro.setText("Cadastrar Livro");
        jBcadastrarLivro.setBorder(null);
        jBcadastrarLivro.setBorderPainted(false);
        jBcadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarLivroActionPerformed(evt);
            }
        });

        jBcadastrarAluno.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarAluno.setText("Cadastrar Aluno");
        jBcadastrarAluno.setBorder(null);
        jBcadastrarAluno.setBorderPainted(false);
        jBcadastrarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPmenuCadastrarLayout = new javax.swing.GroupLayout(jPmenuCadastrar);
        jPmenuCadastrar.setLayout(jPmenuCadastrarLayout);
        jPmenuCadastrarLayout.setHorizontalGroup(
            jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuCadastrarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcadastrarLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcadastrarAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPmenuCadastrarLayout.setVerticalGroup(
            jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuCadastrarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jBcadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPmenuCadastrar);
        jPmenuCadastrar.setBounds(60, 40, 140, 70);

        jPdevolucao.setLayout(null);

        jCBaluno.setPreferredSize(new java.awt.Dimension(70, 20));
        jPdevolucao.add(jCBaluno);
        jCBaluno.setBounds(110, 150, 280, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Data da Devolução");
        jPdevolucao.add(jLabel7);
        jLabel7.setBounds(20, 310, 150, 50);

        jTtabelaDevolucao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Matrícula", "Nome", "Codigo", "Livro", "Data - E", "Data - D"
            }
        ));
        jTtabelaDevolucao.setFocusable(false);
        jScrollPane1.setViewportView(jTtabelaDevolucao);
        if (jTtabelaDevolucao.getColumnModel().getColumnCount() > 0) {
            jTtabelaDevolucao.getColumnModel().getColumn(0).setMaxWidth(20);
            jTtabelaDevolucao.getColumnModel().getColumn(1).setMaxWidth(100);
            jTtabelaDevolucao.getColumnModel().getColumn(3).setMaxWidth(200);
            jTtabelaDevolucao.getColumnModel().getColumn(5).setMaxWidth(150);
            jTtabelaDevolucao.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        jPdevolucao.add(jScrollPane1);
        jScrollPane1.setBounds(40, 490, 600, 110);

        jTcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodigoActionPerformed(evt);
            }
        });
        jPdevolucao.add(jTcodigo);
        jTcodigo.setBounds(440, 240, 180, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID");
        jPdevolucao.add(jLabel6);
        jLabel6.setBounds(30, 60, 50, 40);
        jPdevolucao.add(jSeparator6);
        jSeparator6.setBounds(20, 360, 630, 20);

        jTPid.setFocusable(false);
        jScrollPane3.setViewportView(jTPid);

        jPdevolucao.add(jScrollPane3);
        jScrollPane3.setBounds(110, 70, 80, 30);

        jCBlivro.setPreferredSize(new java.awt.Dimension(70, 20));
        jPdevolucao.add(jCBlivro);
        jCBlivro.setBounds(110, 240, 280, 30);

        jTPdata.setFocusable(false);
        jTPdata.setRequestFocusEnabled(false);
        jTPdata.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTPdata);

        jPdevolucao.add(jScrollPane2);
        jScrollPane2.setBounds(190, 320, 80, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aluno");
        jPdevolucao.add(jLabel3);
        jLabel3.setBounds(30, 110, 60, 100);
        jPdevolucao.add(jSeparator5);
        jSeparator5.setBounds(20, 210, 630, 10);

        jBpesquisarCodigo.setText("Pesquisar por Código");
        jBpesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarCodigoActionPerformed(evt);
            }
        });
        jPdevolucao.add(jBpesquisarCodigo);
        jBpesquisarCodigo.setBounds(450, 280, 160, 23);

        jBefetuar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBefetuar.setText("Efetuar");
        jBefetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBefetuarActionPerformed(evt);
            }
        });
        jPdevolucao.add(jBefetuar);
        jBefetuar.setBounds(250, 380, 180, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Livro");
        jPdevolucao.add(jLabel5);
        jLabel5.setBounds(20, 210, 70, 90);

        jBpesquisarMat.setText("Pesquisar por Matrícula");
        jBpesquisarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarMatActionPerformed(evt);
            }
        });
        jPdevolucao.add(jBpesquisarMat);
        jBpesquisarMat.setBounds(450, 180, 160, 23);
        jPdevolucao.add(jSeparator1);
        jSeparator1.setBounds(20, 60, 630, 20);

        jTmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmatriculaActionPerformed(evt);
            }
        });
        jPdevolucao.add(jTmatricula);
        jTmatricula.setBounds(440, 140, 180, 30);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPdevolucao.add(jSeparator3);
        jSeparator3.setBounds(650, 60, 20, 300);
        jPdevolucao.add(jSeparator2);
        jSeparator2.setBounds(20, 310, 630, 20);
        jPdevolucao.add(jSeparator7);
        jSeparator7.setBounds(20, 110, 630, 10);

        jLabel1.setText("Código");
        jPdevolucao.add(jLabel1);
        jLabel1.setBounds(510, 220, 40, 16);

        jLabel2.setText("Matrícula");
        jPdevolucao.add(jLabel2);
        jLabel2.setBounds(510, 110, 50, 30);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPdevolucao.add(jSeparator9);
        jSeparator9.setBounds(90, 60, 20, 250);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPdevolucao.add(jSeparator10);
        jSeparator10.setBounds(20, 60, 20, 300);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPdevolucao.add(jSeparator11);
        jSeparator11.setBounds(290, 310, 20, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Devoluções");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPdevolucao.add(jLabel4);
        jLabel4.setBounds(260, 20, 150, 30);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPdevolucao.add(jSeparator12);
        jSeparator12.setBounds(400, 110, 20, 200);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Devoluções Recentes");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPdevolucao.add(jLabel8);
        jLabel8.setBounds(240, 450, 200, 30);

        getContentPane().add(jPdevolucao);
        jPdevolucao.setBounds(110, 50, 670, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBefetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBefetuarActionPerformed
        if (lista.getAlunos().size() != 0 || lista.getLivros().size() != 0) {   
            if (!(jCBlivro.getItemCount() == 0 || jCBaluno.getItemCount() == 0)) {
                int id = Integer.valueOf(jTPid.getText());

                String s1 = (String) jCBaluno.getSelectedItem();
                int x = s1.indexOf(" ");
                String matriculaAluno = s1.substring(0, x);

                String s2 = (String) jCBlivro.getSelectedItem();
                x = s2.indexOf(" ");
                String codigoLivro = s2.substring(0, x);

                String nomeAluno = lista.getAlunos().get(lista.buscaAluno(matriculaAluno)).getNome();

                String nomeLivro = lista.getLivros().get(lista.buscaLivro(codigoLivro)).getNome();

                String situacaoAluno = lista.getAlunos().get(lista.buscaAluno(matriculaAluno)).getSituacao();
                
                Emprestimo emp = lista.devolveEmprestimo(lista.buscaEmprestimo(matriculaAluno, codigoLivro));
                
                String situacaoDevolucao;
 
                if (emp != null) {
                    Object[] options = { "Confirmar", "Cancelar" };
                    int veri; 
                    if (situacaoAluno == "P.E.M") {
                        veri = JOptionPane.showOptionDialog(null, "Matrícula: " + matriculaAluno + 
                                                                     "\nAluno: " + nomeAluno +
                                                                     "\nCódigo do Livro: " + codigoLivro + 
                                                                     "\nLivro: " + nomeLivro + 
                                                                     "\n\nEsse aluno terá que pagar MULTA!", 
                                                                  "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                        situacaoDevolucao = "M.";
                    } else {
                        veri = JOptionPane.showOptionDialog(null, "Matrícula: " + matriculaAluno + 
                                                                     "\nAluno: " + nomeAluno +
                                                                     "\nCódigo do Livro: " + codigoLivro + 
                                                                     "\nLivro: " + nomeLivro,
                                                                 "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                        situacaoDevolucao = "---";
                    }

                    if (veri == 0) {
                        lista.armazenaDevolucao(id, emp, data, situacaoDevolucao);
                        
                        int index = lista.buscaEmprestimo(matriculaAluno, codigoLivro);
                        
                        lista.getEmprestimos().get(index).setSituacao("---");
                        lista.getEmprestimos().get(index).setDataDevolucao(data);
                        
                        if (situacaoDevolucao == "---") {
                            lista.colocarSituacao(matriculaAluno, "---", codigoLivro, "---");
                        } else {
                            lista.colocarSituacao(matriculaAluno, "M.", codigoLivro, "---");
                        }
                        tabelaRecentes(lista);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Não há registros de empréstimo pendentes entre:"
                                                                   + "\nMatrícula: " + matriculaAluno + 
                                                                     "\nAluno: " + nomeAluno +
                                                                     "\nCódigo do Livro: " + codigoLivro + 
                                                                     "\nLivro: " + nomeLivro);
                }
                alimentarCB(); 
                jTPid.setText("" + (lista.getDevolucoes().size() + 1));
            } else {
                JOptionPane.showMessageDialog(null, "Não há mais alunos ou livros para fazer devoluções."); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há alunos ou livros cadastrados.");
        }
       
        jCBaluno.requestFocus();
    }//GEN-LAST:event_jBefetuarActionPerformed

    private void jTmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmatriculaActionPerformed

    private void jTcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodigoActionPerformed

    private void jBpesquisarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarMatActionPerformed
        String matricula = jTmatricula.getText();
        boolean veri = false;

        if (matricula.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Matrícula' está vazio."); 
        } else {
            try {
               Integer.valueOf(matricula);
               veri = true;
            } catch (NumberFormatException ex) {
               JOptionPane.showMessageDialog(null, "O campo 'matrícula' apenas aceita números.");
               veri = false;
            }

            if (veri) {
              
                if (lista.buscaAluno(matricula) == -1) {
                   JOptionPane.showMessageDialog(null, "Aluno não encontrado");
                } else {
                    
                    String aluno = lista.getAlunos().get(lista.buscaAluno(matricula)).toString();
                    jCBaluno.setSelectedItem(aluno);  
                }
               
                jTmatricula.setText(null);
            }
        }   
    }//GEN-LAST:event_jBpesquisarMatActionPerformed

    private void jBpesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarCodigoActionPerformed
        String codigo = jTcodigo.getText();
        boolean veri = false;

        if (codigo.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Código' está vazio."); 
        } else {
            try {
               Integer.valueOf(codigo);
               veri = true;
            } catch (NumberFormatException ex) {
               JOptionPane.showMessageDialog(null, "O campo 'código' apenas aceita números.");
               veri = false;
            }

            if (veri) {
                if (lista.buscaLivro(codigo) == -1) {
                    JOptionPane.showMessageDialog(null, "Livro não encontrado");
                } else {
                    String livro = lista.getLivros().get(lista.buscaLivro(codigo)).toString();
                    jCBlivro.setSelectedItem(livro);  
                }
                jTcodigo.setText(null);
            }
        }  
    }//GEN-LAST:event_jBpesquisarCodigoActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBlistarActionPerformed
        tudoInvisivel();
        dispose();
        Tela5_listar tela = new Tela5_listar(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBlistarActionPerformed

    private void jTBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBbuscarActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBbuscarActionPerformed

    private void jTBmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBmultaActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBmultaActionPerformed

    private void jTBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBremoverActionPerformed
        tudoInvisivel();
        dispose();
        Tela7_remover tela = new Tela7_remover(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBremoverActionPerformed

    private void jTBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBcadastrarActionPerformed
        if (jPmenuCadastrar.isVisible()) {
            tudoInvisivel();
        } else {
            tudoInvisivel();
            jPmenuCadastrar.setVisible(true);
        }
    }//GEN-LAST:event_jTBcadastrarActionPerformed

    private void jBsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsair1ActionPerformed
        dispose();
        Tela1_menu tela = new Tela1_menu(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBsair1ActionPerformed

    private void jBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarLivroActionPerformed
        dispose();
        Tela3_cadastrarLivro tela = new Tela3_cadastrarLivro(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarLivroActionPerformed

    private void jBcadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarAlunoActionPerformed
        dispose();
        Tela2_cadastrarAluno tela = new Tela2_cadastrarAluno(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarAlunoActionPerformed

    private void jTBemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBemprestimoActionPerformed
        tudoInvisivel();
        dispose();
        Tela4_emprestimo tela = new Tela4_emprestimo(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBemprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela6_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela6_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela6_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela6_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela6_devolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrarAluno;
    private javax.swing.JButton jBcadastrarLivro;
    private javax.swing.JButton jBefetuar;
    private javax.swing.JButton jBpesquisarCodigo;
    private javax.swing.JButton jBpesquisarMat;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsair1;
    private javax.swing.JComboBox<String> jCBaluno;
    private javax.swing.JComboBox<String> jCBlivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPdevolucao;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPmenuCadastrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jTBbuscar;
    private javax.swing.JToggleButton jTBcadastrar;
    private javax.swing.JToggleButton jTBemprestimo;
    private javax.swing.JToggleButton jTBlistar;
    private javax.swing.JToggleButton jTBmulta;
    private javax.swing.JToggleButton jTBremover;
    private javax.swing.JTextPane jTPdata;
    private javax.swing.JTextPane jTPid;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTmatricula;
    private javax.swing.JTable jTtabelaDevolucao;
    // End of variables declaration//GEN-END:variables

     public void tabelaRecentes(Listas lista) {
        DefaultTableModel recentes = (DefaultTableModel) jTtabelaDevolucao.getModel();

        for (int i = 0; i < 5; i++) {
            recentes.removeRow(0);
        }

        for (int i = lista.getDevolucoes().size() - 1; i > lista.getDevolucoes().size() - 6; i--) {

            if (i >= 0) {
                recentes.addRow(lista.imprimeDevolucao(i));
            } else {
                recentes.addRow(new Object[7]);
            }
        }
    }
     
    public void alimentarCB() {
        jCBaluno.removeAllItems();
        jCBlivro.removeAllItems();
        for (Aluno aluno : lista.getAlunos()) {
            if (aluno.getSituacao() == "P.E" || aluno.getSituacao() == "P.E.M") {
                jCBaluno.addItem(aluno.toString());
            }            
        }
        for (Livro livro : lista.getLivros()) {
            if (livro.getSituacao() == "X") {
                jCBlivro.addItem(livro.toString());
            }
        }
    }
    
     private void tudoInvisivel() {
        jPmenuCadastrar.setVisible(false);
    }

    private void tornarGrid() {
        jPmenuCadastrar.setLayout(new GridLayout(2,1));
    }
}
