/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

import br.com.controller.Listas;
import br.com.controller.Livro;
import java.awt.GridLayout;
import javax.swing.table.DefaultTableModel;

public class Tela7_remover extends javax.swing.JFrame {
    
    Listas lista = new Listas();
    
    public Tela7_remover() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 450);
        
        jLtexto.setText("Matrícula");
        jLtitulo.setText("Remover Alunos");
        tudoInvisivel();
        tornarGrid();
    }
    
    public Tela7_remover(Listas lista) {
        initComponents();
        this.lista = lista;
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 450);
        
        jLtexto.setText("Matrícula");
        jLtitulo.setText("Remover Alunos");
        tudoInvisivel();
        tornarGrid();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPmenuCadastrar = new javax.swing.JPanel();
        jBcadastrarLivro = new javax.swing.JButton();
        jBcadastrarAluno = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBremover = new javax.swing.JButton();
        jLtitulo = new javax.swing.JLabel();
        jRBalunos = new javax.swing.JRadioButton();
        jRBlivros = new javax.swing.JRadioButton();
        jLtexto = new javax.swing.JLabel();
        jTcampo = new javax.swing.JTextField();
        jPmenu = new javax.swing.JPanel();
        jBsair = new javax.swing.JButton();
        jTBremover = new javax.swing.JToggleButton();
        jTBcadastrar = new javax.swing.JToggleButton();
        jBsair1 = new javax.swing.JButton();
        jTBbuscar = new javax.swing.JToggleButton();
        jTBlistar = new javax.swing.JToggleButton();
        jTBemprestimo = new javax.swing.JToggleButton();
        jTBdevolucao = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jPmenuCadastrar.setBackground(new java.awt.Color(51, 51, 255));
        jPmenuCadastrar.setLayout(null);

        jBcadastrarLivro.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarLivro.setText("Cadastrar Livro");
        jBcadastrarLivro.setBorder(null);
        jBcadastrarLivro.setBorderPainted(false);
        jBcadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarLivroActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarLivro);
        jBcadastrarLivro.setBounds(19, 41, 115, 23);

        jBcadastrarAluno.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarAluno.setText("Cadastrar Aluno");
        jBcadastrarAluno.setBorder(null);
        jBcadastrarAluno.setBorderPainted(false);
        jBcadastrarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarAlunoActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarAluno);
        jBcadastrarAluno.setBounds(19, 12, 115, 23);

        getContentPane().add(jPmenuCadastrar);
        jPmenuCadastrar.setBounds(60, 40, 140, 70);

        jPanel1.setLayout(null);

        jBremover.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBremover.setText("Remover");
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });
        jPanel1.add(jBremover);
        jBremover.setBounds(320, 200, 210, 50);

        jLtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulo.setText("Remover Alunos");
        jLtitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLtitulo);
        jLtitulo.setBounds(320, 20, 210, 50);

        buttonGroup1.add(jRBalunos);
        jRBalunos.setSelected(true);
        jRBalunos.setText("Alunos");
        jRBalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBalunosActionPerformed(evt);
            }
        });
        jPanel1.add(jRBalunos);
        jRBalunos.setBounds(660, 110, 98, 21);

        buttonGroup1.add(jRBlivros);
        jRBlivros.setText("Livros");
        jRBlivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBlivrosActionPerformed(evt);
            }
        });
        jPanel1.add(jRBlivros);
        jRBlivros.setBounds(660, 140, 130, 21);

        jLtexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLtexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtexto.setText("Matrícula");
        jPanel1.add(jLtexto);
        jLtexto.setBounds(230, 120, 60, 30);

        jTcampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcampoActionPerformed(evt);
            }
        });
        jPanel1.add(jTcampo);
        jTcampo.setBounds(320, 120, 280, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 40, 850, 310);

        jPmenu.setBackground(new java.awt.Color(0, 0, 255));
        jPmenu.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPmenu.setLayout(null);

        jBsair.setBackground(new java.awt.Color(0, 0, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/sair.png"))); // NOI18N
        jBsair.setBorder(null);
        jBsair.setContentAreaFilled(false);
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        jPmenu.add(jBsair);
        jBsair.setBounds(940, 0, 40, 40);

        jTBremover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBremover.setForeground(new java.awt.Color(255, 255, 255));
        jTBremover.setText("Remover");
        jTBremover.setBorder(null);
        jTBremover.setBorderPainted(false);
        jTBremover.setContentAreaFilled(false);
        jTBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBremover.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBremoverActionPerformed(evt);
            }
        });
        jPmenu.add(jTBremover);
        jTBremover.setBounds(220, 0, 120, 40);

        jTBcadastrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jTBcadastrar.setText("Cadastrar");
        jTBcadastrar.setBorder(null);
        jTBcadastrar.setBorderPainted(false);
        jTBcadastrar.setContentAreaFilled(false);
        jTBcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBcadastrar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBcadastrarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBcadastrar);
        jTBcadastrar.setBounds(70, 0, 130, 40);

        jBsair1.setBackground(new java.awt.Color(0, 0, 255));
        jBsair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/house.png"))); // NOI18N
        jBsair1.setBorder(null);
        jBsair1.setContentAreaFilled(false);
        jBsair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsair1ActionPerformed(evt);
            }
        });
        jPmenu.add(jBsair1);
        jBsair1.setBounds(10, 0, 52, 40);

        jTBbuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTBbuscar.setText("Buscar");
        jTBbuscar.setBorder(null);
        jTBbuscar.setBorderPainted(false);
        jTBbuscar.setContentAreaFilled(false);
        jTBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBbuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBbuscarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBbuscar);
        jTBbuscar.setBounds(510, 0, 120, 40);

        jTBlistar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBlistar.setForeground(new java.awt.Color(255, 255, 255));
        jTBlistar.setText("Listar");
        jTBlistar.setBorder(null);
        jTBlistar.setBorderPainted(false);
        jTBlistar.setContentAreaFilled(false);
        jTBlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBlistar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBlistarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBlistar);
        jTBlistar.setBounds(370, 0, 120, 40);

        jTBemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBemprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jTBemprestimo.setText("Empréstimo");
        jTBemprestimo.setBorder(null);
        jTBemprestimo.setBorderPainted(false);
        jTBemprestimo.setContentAreaFilled(false);
        jTBemprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBemprestimo.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBemprestimoActionPerformed(evt);
            }
        });
        jPmenu.add(jTBemprestimo);
        jTBemprestimo.setBounds(660, 0, 120, 40);

        jTBdevolucao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBdevolucao.setForeground(new java.awt.Color(255, 255, 255));
        jTBdevolucao.setText("Devolução");
        jTBdevolucao.setBorder(null);
        jTBdevolucao.setBorderPainted(false);
        jTBdevolucao.setContentAreaFilled(false);
        jTBdevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBdevolucao.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBdevolucaoActionPerformed(evt);
            }
        });
        jPmenu.add(jTBdevolucao);
        jTBdevolucao.setBounds(800, 0, 142, 40);

        getContentPane().add(jPmenu);
        jPmenu.setBounds(0, 0, 1000, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
        String codigo = jTcampo.getText();
        boolean veri = true, veri2 = false;

        if (jTcampo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo '" + jLtexto.getText() +  "'está vazio.");
        } else {
            try {
                Integer.valueOf(codigo);
                veri = true;
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Erro no campo '" + jLtexto.getText() + "'");
                veri = false;
            }
            if (veri) {
                
                if (jTcampo.getText().length() == 6) {
                    if (jRBalunos.isSelected()) {
                        veri2 = lista.removerAlunos(jTcampo.getText());
                        if (veri2) {
                            JOptionPane.showMessageDialog(null, "Aluno removido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, "Aluno não encontrado\nOu\nAluno indisponível para remoção");
                        }
                    } else {
                        veri2 = lista.removerLivros(jTcampo.getText());
                        if (veri2) {
                            JOptionPane.showMessageDialog(null, "Livro removido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, "Livro não encontrado\nOu\nLivro indisponível para remoção");
                        }
                    }
                    jTcampo.setText(null);
                  
                } else {
                    JOptionPane.showMessageDialog(null, "O campo '" + jLtexto.getText() +"' precisa ter 6 dígitos.");
                }
            }
        }
    }//GEN-LAST:event_jBremoverActionPerformed

    private void jBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarLivroActionPerformed
        dispose();
        Tela7_remover tela = new Tela7_remover(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarLivroActionPerformed

    private void jBcadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarAlunoActionPerformed
        dispose();
        Tela2_cadastrarAluno tela = new Tela2_cadastrarAluno(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarAlunoActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBremoverActionPerformed
        tudoInvisivel();
        dispose();
        Tela7_remover tela = new Tela7_remover(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBremoverActionPerformed

    private void jTBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBcadastrarActionPerformed
        if (jPmenuCadastrar.isVisible()) {
            tudoInvisivel();
        } else {
            tudoInvisivel();
            jPmenuCadastrar.setVisible(true);
        }
    }//GEN-LAST:event_jTBcadastrarActionPerformed

    private void jBsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsair1ActionPerformed
        dispose();
        Tela1_menu tela = new Tela1_menu(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBsair1ActionPerformed

    private void jTBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBbuscarActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBbuscarActionPerformed

    private void jTBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBlistarActionPerformed
        tudoInvisivel();
        dispose();
        Tela5_listar tela = new Tela5_listar(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBlistarActionPerformed

    private void jTBemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBemprestimoActionPerformed
        tudoInvisivel();
        dispose();
        Tela4_emprestimo tela = new Tela4_emprestimo(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBemprestimoActionPerformed

    private void jTBdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBdevolucaoActionPerformed
        tudoInvisivel();
        dispose();
        Tela6_devolucao tela = new Tela6_devolucao(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBdevolucaoActionPerformed

    private void jRBalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBalunosActionPerformed
        if (jRBalunos.isSelected()) {
            jLtitulo.setText("Remover Alunos");
            jLtexto.setText("Matrícula");
        }
    }//GEN-LAST:event_jRBalunosActionPerformed

    private void jRBlivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBlivrosActionPerformed
        if (jRBlivros.isSelected()) {
            jLtitulo.setText("Remover Livros");
            jLtexto.setText("Código");
        }
    }//GEN-LAST:event_jRBlivrosActionPerformed

    private void jTcampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela7_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela7_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela7_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela7_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela7_remover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBcadastrarAluno;
    private javax.swing.JButton jBcadastrarLivro;
    private javax.swing.JButton jBremover;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsair1;
    private javax.swing.JLabel jLtexto;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPmenuCadastrar;
    private javax.swing.JRadioButton jRBalunos;
    private javax.swing.JRadioButton jRBlivros;
    private javax.swing.JToggleButton jTBbuscar;
    private javax.swing.JToggleButton jTBcadastrar;
    private javax.swing.JToggleButton jTBdevolucao;
    private javax.swing.JToggleButton jTBemprestimo;
    private javax.swing.JToggleButton jTBlistar;
    private javax.swing.JToggleButton jTBremover;
    private javax.swing.JTextField jTcampo;
    // End of variables declaration//GEN-END:variables

     private void tudoInvisivel() {
        jPmenuCadastrar.setVisible(false);
    }

    private void tornarGrid() {
        jPmenuCadastrar.setLayout(new GridLayout(2,1));
    }
     
}
