/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

import br.com.controller.Listas;
import br.com.controller.Livro;
import java.awt.GridLayout;
import javax.swing.table.DefaultTableModel;

public class Tela8_buscar extends javax.swing.JFrame {
    
    Listas lista = new Listas();
    
    public Tela8_buscar() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 450);
       
        tudoInvisivel();
        tornarGrid();
    }
    
    public Tela8_buscar(Listas lista) {
        initComponents();
        this.lista = lista;
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 450);

        tudoInvisivel();
        tornarGrid();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPmenuCadastrar = new javax.swing.JPanel();
        jBcadastrarLivro = new javax.swing.JButton();
        jBcadastrarAluno = new javax.swing.JButton();
        jPmenu = new javax.swing.JPanel();
        jBsair = new javax.swing.JButton();
        jTBremover = new javax.swing.JToggleButton();
        jTBcadastrar = new javax.swing.JToggleButton();
        jBsair1 = new javax.swing.JButton();
        jTBbuscar = new javax.swing.JToggleButton();
        jTBlistar = new javax.swing.JToggleButton();
        jTBemprestimo = new javax.swing.JToggleButton();
        jTBdevolucao = new javax.swing.JToggleButton();
        jPbuscas = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jPemprestimos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTemprestimos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTFcodigoEmprestimo = new javax.swing.JTextField();
        jBbuscarE = new javax.swing.JButton();
        jTFmatriculaEmprestimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPdevolucoes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFalunos1 = new javax.swing.JTextField();
        jBbuscarA1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTdevolucoes = new javax.swing.JTable();
        jPalunos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTalunos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTFalunos = new javax.swing.JTextField();
        jBbuscarA = new javax.swing.JButton();
        jPlivros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlivros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTFlivros = new javax.swing.JTextField();
        jBbuscarL = new javax.swing.JButton();
        jLtexto1 = new javax.swing.JLabel();
        jCBopcoes = new javax.swing.JComboBox<>();
        jBselecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jPmenuCadastrar.setBackground(new java.awt.Color(51, 51, 255));
        jPmenuCadastrar.setLayout(null);

        jBcadastrarLivro.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarLivro.setText("Cadastrar Livro");
        jBcadastrarLivro.setBorder(null);
        jBcadastrarLivro.setBorderPainted(false);
        jBcadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarLivroActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarLivro);
        jBcadastrarLivro.setBounds(19, 41, 115, 23);

        jBcadastrarAluno.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarAluno.setText("Cadastrar Aluno");
        jBcadastrarAluno.setBorder(null);
        jBcadastrarAluno.setBorderPainted(false);
        jBcadastrarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarAlunoActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarAluno);
        jBcadastrarAluno.setBounds(19, 12, 115, 23);

        getContentPane().add(jPmenuCadastrar);
        jPmenuCadastrar.setBounds(60, 40, 140, 70);

        jPmenu.setBackground(new java.awt.Color(0, 0, 255));
        jPmenu.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPmenu.setLayout(null);

        jBsair.setBackground(new java.awt.Color(0, 0, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/sair.png"))); // NOI18N
        jBsair.setBorder(null);
        jBsair.setContentAreaFilled(false);
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        jPmenu.add(jBsair);
        jBsair.setBounds(940, 0, 40, 40);

        jTBremover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBremover.setForeground(new java.awt.Color(255, 255, 255));
        jTBremover.setText("Remover");
        jTBremover.setBorder(null);
        jTBremover.setBorderPainted(false);
        jTBremover.setContentAreaFilled(false);
        jTBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBremover.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBremoverActionPerformed(evt);
            }
        });
        jPmenu.add(jTBremover);
        jTBremover.setBounds(220, 0, 120, 40);

        jTBcadastrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jTBcadastrar.setText("Cadastrar");
        jTBcadastrar.setBorder(null);
        jTBcadastrar.setBorderPainted(false);
        jTBcadastrar.setContentAreaFilled(false);
        jTBcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBcadastrar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBcadastrarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBcadastrar);
        jTBcadastrar.setBounds(70, 0, 130, 40);

        jBsair1.setBackground(new java.awt.Color(0, 0, 255));
        jBsair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/house.png"))); // NOI18N
        jBsair1.setBorder(null);
        jBsair1.setContentAreaFilled(false);
        jBsair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsair1ActionPerformed(evt);
            }
        });
        jPmenu.add(jBsair1);
        jBsair1.setBounds(10, 0, 52, 40);

        jTBbuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTBbuscar.setText("Buscar");
        jTBbuscar.setBorder(null);
        jTBbuscar.setBorderPainted(false);
        jTBbuscar.setContentAreaFilled(false);
        jTBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBbuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBbuscarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBbuscar);
        jTBbuscar.setBounds(510, 0, 120, 40);

        jTBlistar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBlistar.setForeground(new java.awt.Color(255, 255, 255));
        jTBlistar.setText("Listar");
        jTBlistar.setBorder(null);
        jTBlistar.setBorderPainted(false);
        jTBlistar.setContentAreaFilled(false);
        jTBlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBlistar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBlistarActionPerformed(evt);
            }
        });
        jPmenu.add(jTBlistar);
        jTBlistar.setBounds(370, 0, 120, 40);

        jTBemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBemprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jTBemprestimo.setText("Empréstimo");
        jTBemprestimo.setBorder(null);
        jTBemprestimo.setBorderPainted(false);
        jTBemprestimo.setContentAreaFilled(false);
        jTBemprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBemprestimo.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBemprestimoActionPerformed(evt);
            }
        });
        jPmenu.add(jTBemprestimo);
        jTBemprestimo.setBounds(660, 0, 120, 40);

        jTBdevolucao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBdevolucao.setForeground(new java.awt.Color(255, 255, 255));
        jTBdevolucao.setText("Devolução");
        jTBdevolucao.setBorder(null);
        jTBdevolucao.setBorderPainted(false);
        jTBdevolucao.setContentAreaFilled(false);
        jTBdevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBdevolucao.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBdevolucaoActionPerformed(evt);
            }
        });
        jPmenu.add(jTBdevolucao);
        jTBdevolucao.setBounds(800, 0, 142, 40);

        getContentPane().add(jPmenu);
        jPmenu.setBounds(0, 0, 1000, 40);

        jPbuscas.setLayout(null);

        jLtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulo.setText("Buscar");
        jLtitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPbuscas.add(jLtitulo);
        jLtitulo.setBounds(240, 0, 140, 50);

        jPemprestimos.setLayout(null);

        jTemprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Matrícula", "Aluno", "Código", "Livro", "Data - E", "Data - D", "Situação"
            }
        ));
        jScrollPane4.setViewportView(jTemprestimos);
        if (jTemprestimos.getColumnModel().getColumnCount() > 0) {
            jTemprestimos.getColumnModel().getColumn(0).setMaxWidth(20);
            jTemprestimos.getColumnModel().getColumn(1).setMaxWidth(200);
            jTemprestimos.getColumnModel().getColumn(3).setMaxWidth(200);
            jTemprestimos.getColumnModel().getColumn(5).setMaxWidth(200);
            jTemprestimos.getColumnModel().getColumn(6).setMaxWidth(200);
            jTemprestimos.getColumnModel().getColumn(7).setMaxWidth(80);
        }

        jPemprestimos.add(jScrollPane4);
        jScrollPane4.setBounds(40, 160, 452, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Código");
        jPemprestimos.add(jLabel4);
        jLabel4.setBounds(40, 70, 90, 20);

        jTFcodigoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcodigoEmprestimoActionPerformed(evt);
            }
        });
        jPemprestimos.add(jTFcodigoEmprestimo);
        jTFcodigoEmprestimo.setBounds(150, 70, 250, 22);

        jBbuscarE.setText("Buscar");
        jPemprestimos.add(jBbuscarE);
        jBbuscarE.setBounds(190, 110, 130, 30);

        jTFmatriculaEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFmatriculaEmprestimoActionPerformed(evt);
            }
        });
        jPemprestimos.add(jTFmatriculaEmprestimo);
        jTFmatriculaEmprestimo.setBounds(150, 30, 250, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Matrícula");
        jPemprestimos.add(jLabel5);
        jLabel5.setBounds(40, 30, 90, 20);

        jPbuscas.add(jPemprestimos);
        jPemprestimos.setBounds(60, 60, 520, 240);

        jPdevolucoes.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Matrícula");
        jPdevolucoes.add(jLabel3);
        jLabel3.setBounds(40, 40, 90, 20);

        jTFalunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFalunos1ActionPerformed(evt);
            }
        });
        jPdevolucoes.add(jTFalunos1);
        jTFalunos1.setBounds(150, 40, 250, 22);

        jBbuscarA1.setText("Buscar");
        jPdevolucoes.add(jBbuscarA1);
        jBbuscarA1.setBounds(190, 110, 130, 30);

        jTdevolucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Matrícula", "Aluno", "Código", "Livro", "Data - E", "Data - D", "Situação"
            }
        ));
        jScrollPane5.setViewportView(jTdevolucoes);
        if (jTdevolucoes.getColumnModel().getColumnCount() > 0) {
            jTdevolucoes.getColumnModel().getColumn(0).setMaxWidth(20);
            jTdevolucoes.getColumnModel().getColumn(1).setMaxWidth(200);
            jTdevolucoes.getColumnModel().getColumn(3).setMaxWidth(200);
            jTdevolucoes.getColumnModel().getColumn(5).setMaxWidth(200);
            jTdevolucoes.getColumnModel().getColumn(6).setMaxWidth(200);
            jTdevolucoes.getColumnModel().getColumn(7).setMaxWidth(80);
        }

        jPdevolucoes.add(jScrollPane5);
        jScrollPane5.setBounds(40, 160, 452, 50);

        jPbuscas.add(jPdevolucoes);
        jPdevolucoes.setBounds(60, 60, 520, 240);

        jPalunos.setLayout(null);

        jTalunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Matrícula", "Nome", "Série", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jTalunos);
        if (jTalunos.getColumnModel().getColumnCount() > 0) {
            jTalunos.getColumnModel().getColumn(0).setMaxWidth(20);
            jTalunos.getColumnModel().getColumn(1).setMaxWidth(200);
            jTalunos.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPalunos.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 452, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matrícula");
        jPalunos.add(jLabel1);
        jLabel1.setBounds(40, 40, 90, 20);

        jTFalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFalunosActionPerformed(evt);
            }
        });
        jPalunos.add(jTFalunos);
        jTFalunos.setBounds(150, 40, 250, 22);

        jBbuscarA.setText("Buscar");
        jPalunos.add(jBbuscarA);
        jBbuscarA.setBounds(190, 110, 130, 30);

        jPbuscas.add(jPalunos);
        jPalunos.setBounds(60, 60, 520, 240);

        jPlivros.setLayout(null);

        jTlivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Código", "Nome", "Autor", "Situação"
            }
        ));
        jScrollPane2.setViewportView(jTlivros);
        if (jTlivros.getColumnModel().getColumnCount() > 0) {
            jTlivros.getColumnModel().getColumn(0).setMaxWidth(20);
            jTlivros.getColumnModel().getColumn(1).setMaxWidth(200);
            jTlivros.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPlivros.add(jScrollPane2);
        jScrollPane2.setBounds(30, 160, 452, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código");
        jPlivros.add(jLabel2);
        jLabel2.setBounds(40, 40, 90, 20);

        jTFlivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFlivrosActionPerformed(evt);
            }
        });
        jPlivros.add(jTFlivros);
        jTFlivros.setBounds(140, 40, 250, 22);

        jBbuscarL.setText("Buscar");
        jPlivros.add(jBbuscarL);
        jBbuscarL.setBounds(180, 110, 130, 30);

        jPbuscas.add(jPlivros);
        jPlivros.setBounds(70, 60, 520, 240);

        getContentPane().add(jPbuscas);
        jPbuscas.setBounds(160, 50, 630, 460);

        jLtexto1.setText("OPções para Buscar");
        getContentPane().add(jLtexto1);
        jLtexto1.setBounds(810, 60, 140, 16);

        jCBopcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alunos", "Livros", "Empréstimos. Devoluções" }));
        getContentPane().add(jCBopcoes);
        jCBopcoes.setBounds(800, 90, 170, 22);

        jBselecionar.setText("Escolher");
        getContentPane().add(jBselecionar);
        jBselecionar.setBounds(840, 130, 74, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarLivroActionPerformed
        dispose();
        Tela8_buscar tela = new Tela8_buscar(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarLivroActionPerformed

    private void jBcadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarAlunoActionPerformed
        dispose();
        Tela2_cadastrarAluno tela = new Tela2_cadastrarAluno(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarAlunoActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBremoverActionPerformed
        tudoInvisivel();
        dispose();
        Tela8_buscar tela = new Tela8_buscar(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBremoverActionPerformed

    private void jTBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBcadastrarActionPerformed
        if (jPmenuCadastrar.isVisible()) {
            tudoInvisivel();
        } else {
            tudoInvisivel();
            jPmenuCadastrar.setVisible(true);
        }
    }//GEN-LAST:event_jTBcadastrarActionPerformed

    private void jBsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsair1ActionPerformed
        dispose();
        Tela1_menu tela = new Tela1_menu(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBsair1ActionPerformed

    private void jTBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBbuscarActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBbuscarActionPerformed

    private void jTBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBlistarActionPerformed
        tudoInvisivel();
        dispose();
        Tela5_listar tela = new Tela5_listar(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBlistarActionPerformed

    private void jTBemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBemprestimoActionPerformed
        tudoInvisivel();
        dispose();
        Tela4_emprestimo tela = new Tela4_emprestimo(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBemprestimoActionPerformed

    private void jTBdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBdevolucaoActionPerformed
        tudoInvisivel();
        dispose();
        Tela6_devolucao tela = new Tela6_devolucao(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBdevolucaoActionPerformed

    private void jTFalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFalunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFalunosActionPerformed

    private void jTFlivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFlivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFlivrosActionPerformed

    private void jTFalunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFalunos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFalunos1ActionPerformed

    private void jTFcodigoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcodigoEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcodigoEmprestimoActionPerformed

    private void jTFmatriculaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFmatriculaEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFmatriculaEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela8_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela8_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela8_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela8_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela8_buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBbuscarA;
    private javax.swing.JButton jBbuscarA1;
    private javax.swing.JButton jBbuscarE;
    private javax.swing.JButton jBbuscarL;
    private javax.swing.JButton jBcadastrarAluno;
    private javax.swing.JButton jBcadastrarLivro;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsair1;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JComboBox<String> jCBopcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLtexto1;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPalunos;
    private javax.swing.JPanel jPbuscas;
    private javax.swing.JPanel jPdevolucoes;
    private javax.swing.JPanel jPemprestimos;
    private javax.swing.JPanel jPlivros;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPmenuCadastrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jTBbuscar;
    private javax.swing.JToggleButton jTBcadastrar;
    private javax.swing.JToggleButton jTBdevolucao;
    private javax.swing.JToggleButton jTBemprestimo;
    private javax.swing.JToggleButton jTBlistar;
    private javax.swing.JToggleButton jTBremover;
    private javax.swing.JTextField jTFalunos;
    private javax.swing.JTextField jTFalunos1;
    private javax.swing.JTextField jTFcodigoEmprestimo;
    private javax.swing.JTextField jTFlivros;
    private javax.swing.JTextField jTFmatriculaEmprestimo;
    private javax.swing.JTable jTalunos;
    private javax.swing.JTable jTdevolucoes;
    private javax.swing.JTable jTemprestimos;
    private javax.swing.JTable jTlivros;
    // End of variables declaration//GEN-END:variables

     private void tudoInvisivel() {
        jPmenuCadastrar.setVisible(false);
    }

    private void tornarGrid() {
        jPmenuCadastrar.setLayout(new GridLayout(2,1));
    }
     
}
