/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.Emprestimo;
import java.awt.GridLayout;
import java.awt.Toolkit;

import br.com.controller.Listas;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class Tela1_menu extends javax.swing.JFrame {

    Listas lista = new Listas();
    LocalDate data = LocalDate.now();
    
    public Tela1_menu() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 600);
        
        tudoInvisivel();
        tornarGrid();
        verificaDados();
    }
    
    public Tela1_menu(Listas lista) {
        initComponents();
        this.lista = lista;
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(1000, 600);
        
        tudoInvisivel();
        tornarGrid();
        verificaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPmenuCadastrar = new javax.swing.JPanel();
        jBcadastrarLivro = new javax.swing.JButton();
        jBcadastrarAluno = new javax.swing.JButton();
        jPmenu = new javax.swing.JPanel();
        jBsair = new javax.swing.JButton();
        jTBlistar = new javax.swing.JToggleButton();
        jTBbuscar = new javax.swing.JToggleButton();
        jTBemprestimo = new javax.swing.JToggleButton();
        jTBdevolucao = new javax.swing.JToggleButton();
        jTBmulta = new javax.swing.JToggleButton();
        jTBremover = new javax.swing.JToggleButton();
        jTBcadastrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPmenuCadastrar.setBackground(new java.awt.Color(51, 51, 255));

        jBcadastrarLivro.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarLivro.setText("Cadastrar Livro");
        jBcadastrarLivro.setBorder(null);
        jBcadastrarLivro.setBorderPainted(false);
        jBcadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarLivroActionPerformed(evt);
            }
        });

        jBcadastrarAluno.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarAluno.setText("Cadastrar Aluno");
        jBcadastrarAluno.setBorder(null);
        jBcadastrarAluno.setBorderPainted(false);
        jBcadastrarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPmenuCadastrarLayout = new javax.swing.GroupLayout(jPmenuCadastrar);
        jPmenuCadastrar.setLayout(jPmenuCadastrarLayout);
        jPmenuCadastrarLayout.setHorizontalGroup(
            jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuCadastrarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcadastrarLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcadastrarAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPmenuCadastrarLayout.setVerticalGroup(
            jPmenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuCadastrarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jBcadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPmenuCadastrar);
        jPmenuCadastrar.setBounds(0, 40, 140, 70);

        jPmenu.setBackground(new java.awt.Color(0, 0, 255));
        jPmenu.setPreferredSize(new java.awt.Dimension(1000, 40));

        jBsair.setBackground(new java.awt.Color(0, 0, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/sair.png"))); // NOI18N
        jBsair.setBorder(null);
        jBsair.setContentAreaFilled(false);
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jTBlistar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBlistar.setForeground(new java.awt.Color(255, 255, 255));
        jTBlistar.setText("Listar");
        jTBlistar.setBorder(null);
        jTBlistar.setBorderPainted(false);
        jTBlistar.setContentAreaFilled(false);
        jTBlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBlistar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBlistarActionPerformed(evt);
            }
        });

        jTBbuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTBbuscar.setText("Buscar");
        jTBbuscar.setBorder(null);
        jTBbuscar.setBorderPainted(false);
        jTBbuscar.setContentAreaFilled(false);
        jTBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBbuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBbuscarActionPerformed(evt);
            }
        });

        jTBemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBemprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jTBemprestimo.setText("Empréstimo");
        jTBemprestimo.setBorder(null);
        jTBemprestimo.setBorderPainted(false);
        jTBemprestimo.setContentAreaFilled(false);
        jTBemprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBemprestimo.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBemprestimoActionPerformed(evt);
            }
        });

        jTBdevolucao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBdevolucao.setForeground(new java.awt.Color(255, 255, 255));
        jTBdevolucao.setText("Devolução");
        jTBdevolucao.setBorder(null);
        jTBdevolucao.setBorderPainted(false);
        jTBdevolucao.setContentAreaFilled(false);
        jTBdevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBdevolucao.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBdevolucaoActionPerformed(evt);
            }
        });

        jTBmulta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBmulta.setForeground(new java.awt.Color(255, 255, 255));
        jTBmulta.setText("Multa");
        jTBmulta.setBorder(null);
        jTBmulta.setBorderPainted(false);
        jTBmulta.setContentAreaFilled(false);
        jTBmulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBmulta.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBmultaActionPerformed(evt);
            }
        });

        jTBremover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBremover.setForeground(new java.awt.Color(255, 255, 255));
        jTBremover.setText("Remover");
        jTBremover.setBorder(null);
        jTBremover.setBorderPainted(false);
        jTBremover.setContentAreaFilled(false);
        jTBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBremover.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBremoverActionPerformed(evt);
            }
        });

        jTBcadastrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jTBcadastrar.setText("Cadastrar");
        jTBcadastrar.setBorder(null);
        jTBcadastrar.setBorderPainted(false);
        jTBcadastrar.setContentAreaFilled(false);
        jTBcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBcadastrar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBcadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPmenuLayout = new javax.swing.GroupLayout(jPmenu);
        jPmenu.setLayout(jPmenuLayout);
        jPmenuLayout.setHorizontalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBlistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTBdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsair)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPmenuLayout.setVerticalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBlistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPmenu);
        jPmenu.setBounds(0, 0, 1000, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBcadastrarActionPerformed
        if (jPmenuCadastrar.isVisible()) {
            tudoInvisivel();
        } else {
            tudoInvisivel();
            jPmenuCadastrar.setVisible(true);
        }
    }//GEN-LAST:event_jTBcadastrarActionPerformed

    private void jTBmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBmultaActionPerformed
        tudoInvisivel();
        {
        }    }//GEN-LAST:event_jTBmultaActionPerformed

    private void jTBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBlistarActionPerformed
        tudoInvisivel();
        dispose();
        Tela5_listar tela = new Tela5_listar(lista);
        tela.setVisible(true);
                                          
    }//GEN-LAST:event_jTBlistarActionPerformed

    private void jTBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBremoverActionPerformed
        tudoInvisivel();
        dispose();
        Tela7_remover tela = new Tela7_remover(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBremoverActionPerformed

    private void jTBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBbuscarActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBbuscarActionPerformed

    private void jTBemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBemprestimoActionPerformed
        tudoInvisivel();
        dispose();
        Tela4_emprestimo tela = new Tela4_emprestimo(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBemprestimoActionPerformed

    private void jTBdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBdevolucaoActionPerformed
        tudoInvisivel();
        dispose();
        Tela6_devolucao tela = new Tela6_devolucao(lista);
        tela.setVisible(true);
       
    }//GEN-LAST:event_jTBdevolucaoActionPerformed

    private void jBcadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarAlunoActionPerformed
        dispose();
        Tela2_cadastrarAluno tela = new Tela2_cadastrarAluno(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarAlunoActionPerformed

    private void jBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarLivroActionPerformed
        dispose();
        Tela3_cadastrarLivro tela = new Tela3_cadastrarLivro(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrarAluno;
    private javax.swing.JButton jBcadastrarLivro;
    private javax.swing.JButton jBsair;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPmenuCadastrar;
    private javax.swing.JToggleButton jTBbuscar;
    private javax.swing.JToggleButton jTBcadastrar;
    private javax.swing.JToggleButton jTBdevolucao;
    private javax.swing.JToggleButton jTBemprestimo;
    private javax.swing.JToggleButton jTBlistar;
    private javax.swing.JToggleButton jTBmulta;
    private javax.swing.JToggleButton jTBremover;
    // End of variables declaration//GEN-END:variables
    
    private void tudoInvisivel() {
        jPmenuCadastrar.setVisible(false);
    }

    private void tornarGrid() {
        jPmenuCadastrar.setLayout(new GridLayout(2,1));
    }
    
    public void verificaDados() {
        
        if (lista.getEmprestimos().size() != 0) {
            for (int i = 0; i < lista.getEmprestimos().size(); i++) {
                if (data.isAfter(lista.getEmprestimos().get(i).getDataDevolucao())&& lista.getEmprestimos().get(i).getSituacao().equals("X")) {
                    lista.colocarSituacao(lista.getEmprestimos().get(i).getMatriculaAluno(),
                            "P.E.M", 
                            lista.getEmprestimos().get(i).getCodigoLivro(),
                            "X");
                }
            }
        }
    }
}
