/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.Aluno;
import br.com.controller.Emprestimo;
import br.com.controller.Listas;
import br.com.controller.Livro;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kotot
 */
public class Tela5_listar extends javax.swing.JFrame {

    Listas lista = new Listas();
    
    DefaultTableModel tabelaAlunos, tabelaLivros, tabelaEmprestimos, tabelaDevolucoes;
    
    public Tela5_listar(Listas lista) {
        initComponents();
        this.lista = lista;
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(995, 600);
        
        tornarInvisivel();
        jPTalunos.setVisible(true);
        tabelaAlunos = lista.imprimeTodosAlunos(jTlistaAlunos);
        tabelaLivros = lista.imprimeTodosLivros(jTlistaLivros);
        tabelaEmprestimos = lista.imprimeTodosEmprestimos(jTlistaEmprestimos);
        tabelaDevolucoes = lista.imprimeTodosDevolucoes(jTlistaDevolucoes);
        tudoInvisivel();
        tornarGrid();
    }
    
    public Tela5_listar() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(this.getClass().getResource("images/icon.png")));
        this.setLocationRelativeTo(null);
        this.setSize(995, 600);
        
        tornarInvisivel();
        jPTalunos.setVisible(true);
        tabelaAlunos = lista.imprimeTodosAlunos(jTlistaAlunos);
        tabelaLivros = lista.imprimeTodosLivros(jTlistaLivros);
        tabelaEmprestimos = lista.imprimeTodosEmprestimos(jTlistaEmprestimos);
        tudoInvisivel();
        tornarGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPmenu = new javax.swing.JPanel();
        jBsair = new javax.swing.JButton();
        jTBdevolucao = new javax.swing.JToggleButton();
        jTBmulta = new javax.swing.JToggleButton();
        jTBremover = new javax.swing.JToggleButton();
        jTBcadastrar = new javax.swing.JToggleButton();
        jBsair1 = new javax.swing.JButton();
        jTBemprestimo = new javax.swing.JToggleButton();
        jTBbuscar = new javax.swing.JToggleButton();
        jPmenuCadastrar = new javax.swing.JPanel();
        jBcadastrarLivro = new javax.swing.JButton();
        jBcadastrarAluno = new javax.swing.JButton();
        jPlistas = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jPTalunos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaAlunos = new javax.swing.JTable();
        jPTlivros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlistaLivros = new javax.swing.JTable();
        jPTemprestimos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTlistaEmprestimos = new javax.swing.JTable();
        jPTdevolucoes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTlistaDevolucoes = new javax.swing.JTable();
        jPlistar = new javax.swing.JPanel();
        jCBopcoes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(995, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPmenu.setBackground(new java.awt.Color(0, 0, 255));
        jPmenu.setPreferredSize(new java.awt.Dimension(1000, 40));

        jBsair.setBackground(new java.awt.Color(0, 0, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/sair.png"))); // NOI18N
        jBsair.setBorder(null);
        jBsair.setContentAreaFilled(false);
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jTBdevolucao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBdevolucao.setForeground(new java.awt.Color(255, 255, 255));
        jTBdevolucao.setText("Devolução");
        jTBdevolucao.setBorder(null);
        jTBdevolucao.setBorderPainted(false);
        jTBdevolucao.setContentAreaFilled(false);
        jTBdevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBdevolucao.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBdevolucaoActionPerformed(evt);
            }
        });

        jTBmulta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBmulta.setForeground(new java.awt.Color(255, 255, 255));
        jTBmulta.setText("Multa");
        jTBmulta.setBorder(null);
        jTBmulta.setBorderPainted(false);
        jTBmulta.setContentAreaFilled(false);
        jTBmulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBmulta.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBmultaActionPerformed(evt);
            }
        });

        jTBremover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBremover.setForeground(new java.awt.Color(255, 255, 255));
        jTBremover.setText("Remover");
        jTBremover.setBorder(null);
        jTBremover.setBorderPainted(false);
        jTBremover.setContentAreaFilled(false);
        jTBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBremover.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBremoverActionPerformed(evt);
            }
        });

        jTBcadastrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jTBcadastrar.setText("Cadastrar");
        jTBcadastrar.setBorder(null);
        jTBcadastrar.setBorderPainted(false);
        jTBcadastrar.setContentAreaFilled(false);
        jTBcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBcadastrar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBcadastrarActionPerformed(evt);
            }
        });

        jBsair1.setBackground(new java.awt.Color(0, 0, 255));
        jBsair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/images/house.png"))); // NOI18N
        jBsair1.setBorder(null);
        jBsair1.setContentAreaFilled(false);
        jBsair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsair1ActionPerformed(evt);
            }
        });

        jTBemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBemprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jTBemprestimo.setText("Empréstimo");
        jTBemprestimo.setBorder(null);
        jTBemprestimo.setBorderPainted(false);
        jTBemprestimo.setContentAreaFilled(false);
        jTBemprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBemprestimo.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBemprestimoActionPerformed(evt);
            }
        });

        jTBbuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTBbuscar.setText("Buscar");
        jTBbuscar.setBorder(null);
        jTBbuscar.setBorderPainted(false);
        jTBbuscar.setContentAreaFilled(false);
        jTBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTBbuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        jTBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPmenuLayout = new javax.swing.GroupLayout(jPmenu);
        jPmenu.setLayout(jPmenuLayout);
        jPmenuLayout.setHorizontalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBsair1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTBdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBsair)
                .addGap(32, 32, 32))
        );
        jPmenuLayout.setVerticalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBremover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBsair1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBsair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPmenu);
        jPmenu.setBounds(0, 0, 1000, 40);

        jPmenuCadastrar.setBackground(new java.awt.Color(51, 51, 255));
        jPmenuCadastrar.setLayout(null);

        jBcadastrarLivro.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarLivro.setText("Cadastrar Livro");
        jBcadastrarLivro.setBorder(null);
        jBcadastrarLivro.setBorderPainted(false);
        jBcadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarLivroActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarLivro);
        jBcadastrarLivro.setBounds(19, 41, 115, 23);

        jBcadastrarAluno.setBackground(new java.awt.Color(51, 51, 255));
        jBcadastrarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBcadastrarAluno.setText("Cadastrar Aluno");
        jBcadastrarAluno.setBorder(null);
        jBcadastrarAluno.setBorderPainted(false);
        jBcadastrarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarAlunoActionPerformed(evt);
            }
        });
        jPmenuCadastrar.add(jBcadastrarAluno);
        jBcadastrarAluno.setBounds(19, 12, 115, 23);

        getContentPane().add(jPmenuCadastrar);
        jPmenuCadastrar.setBounds(60, 40, 160, 70);

        jPlistas.setLayout(null);

        jLtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulo.setText("Tabela de Alunos");
        jLtitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPlistas.add(jLtitulo);
        jLtitulo.setBounds(280, 10, 190, 50);

        jPTalunos.setLayout(null);

        jTlistaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Matrícula", "Nome", "Série", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jTlistaAlunos);
        if (jTlistaAlunos.getColumnModel().getColumnCount() > 0) {
            jTlistaAlunos.getColumnModel().getColumn(0).setMaxWidth(40);
            jTlistaAlunos.getColumnModel().getColumn(1).setMaxWidth(200);
            jTlistaAlunos.getColumnModel().getColumn(3).setMaxWidth(50);
            jTlistaAlunos.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jPTalunos.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 702, 402);

        jPlistas.add(jPTalunos);
        jPTalunos.setBounds(20, 60, 730, 420);

        jPTlivros.setLayout(null);

        jTlistaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Código", "Nome", "Autor", "Situação"
            }
        ));
        jScrollPane2.setViewportView(jTlistaLivros);
        if (jTlistaLivros.getColumnModel().getColumnCount() > 0) {
            jTlistaLivros.getColumnModel().getColumn(0).setMaxWidth(40);
            jTlistaLivros.getColumnModel().getColumn(1).setMaxWidth(200);
            jTlistaLivros.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jPTlivros.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 702, 402);

        jPlistas.add(jPTlivros);
        jPTlivros.setBounds(20, 60, 730, 420);

        jPTemprestimos.setLayout(null);

        jTlistaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Matrícula", "Aluno", "Código", "Livro", "Data - E", "Data - D", "Situação"
            }
        ));
        jScrollPane3.setViewportView(jTlistaEmprestimos);
        if (jTlistaEmprestimos.getColumnModel().getColumnCount() > 0) {
            jTlistaEmprestimos.getColumnModel().getColumn(0).setMaxWidth(20);
            jTlistaEmprestimos.getColumnModel().getColumn(1).setMaxWidth(200);
            jTlistaEmprestimos.getColumnModel().getColumn(3).setMaxWidth(200);
            jTlistaEmprestimos.getColumnModel().getColumn(5).setMaxWidth(80);
            jTlistaEmprestimos.getColumnModel().getColumn(6).setMaxWidth(80);
            jTlistaEmprestimos.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPTemprestimos.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 700, 402);

        jPlistas.add(jPTemprestimos);
        jPTemprestimos.setBounds(20, 60, 730, 420);

        jPTdevolucoes.setLayout(null);

        jTlistaDevolucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Matrícula", "Aluno", "Código", "Livro", "Data - E", "Data - D", "Situação"
            }
        ));
        jScrollPane4.setViewportView(jTlistaDevolucoes);
        if (jTlistaDevolucoes.getColumnModel().getColumnCount() > 0) {
            jTlistaDevolucoes.getColumnModel().getColumn(0).setMaxWidth(20);
            jTlistaDevolucoes.getColumnModel().getColumn(1).setMaxWidth(200);
            jTlistaDevolucoes.getColumnModel().getColumn(3).setMaxWidth(200);
            jTlistaDevolucoes.getColumnModel().getColumn(5).setMaxWidth(80);
            jTlistaDevolucoes.getColumnModel().getColumn(6).setMaxWidth(80);
            jTlistaDevolucoes.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPTdevolucoes.add(jScrollPane4);
        jScrollPane4.setBounds(10, 20, 700, 402);

        jPlistas.add(jPTdevolucoes);
        jPTdevolucoes.setBounds(20, 60, 730, 420);

        getContentPane().add(jPlistas);
        jPlistas.setBounds(0, 60, 760, 500);

        jPlistar.setLayout(null);

        jCBopcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alunos", "Livros", "Emprestimos", "Devoluções" }));
        jPlistar.add(jCBopcoes);
        jCBopcoes.setBounds(10, 40, 190, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPlistar.add(jButton1);
        jButton1.setBounds(50, 80, 100, 30);

        jLabel4.setText("Opções para Listas");
        jPlistar.add(jLabel4);
        jLabel4.setBounds(50, 10, 110, 20);

        getContentPane().add(jPlistar);
        jPlistar.setBounds(760, 110, 210, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String opcao = "" + jCBopcoes.getSelectedItem();
        
        switch (opcao) {
            case "Alunos":
                tornarInvisivel();
                jPTalunos.setVisible(true);
                jLtitulo.setText("Tabela Alunos");
                break;
            case "Livros":
                tornarInvisivel();
                jPTlivros.setVisible(true);
                jLtitulo.setText("Tabela Livros");
                break;
            case "Emprestimos":
                tornarInvisivel();
                jPTemprestimos.setVisible(true);
                jLtitulo.setText("Tabela Empréstimos");
                break;
                
            case "Devoluções":
                tornarInvisivel();
                jPTdevolucoes.setVisible(true);
                jLtitulo.setText("Tabela Devoluções");
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarLivroActionPerformed
        dispose();
        Tela3_cadastrarLivro tela = new Tela3_cadastrarLivro(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarLivroActionPerformed

    private void jBcadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarAlunoActionPerformed
        dispose();
        Tela2_cadastrarAluno tela = new Tela2_cadastrarAluno(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadastrarAlunoActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBbuscarActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBbuscarActionPerformed

    private void jTBdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBdevolucaoActionPerformed
        tudoInvisivel();
        dispose();
        Tela6_devolucao tela = new Tela6_devolucao(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBdevolucaoActionPerformed

    private void jTBmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBmultaActionPerformed
        tudoInvisivel();
    }//GEN-LAST:event_jTBmultaActionPerformed

    private void jTBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBremoverActionPerformed
        tudoInvisivel();
        dispose();
        Tela7_remover tela = new Tela7_remover(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBremoverActionPerformed

    private void jTBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBcadastrarActionPerformed
        if (jPmenuCadastrar.isVisible()) {
            tudoInvisivel();
        } else {
            tudoInvisivel();
            jPmenuCadastrar.setVisible(true);
        }
    }//GEN-LAST:event_jTBcadastrarActionPerformed

    private void jBsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsair1ActionPerformed
        dispose();
        Tela1_menu tela = new Tela1_menu(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jBsair1ActionPerformed

    private void jTBemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBemprestimoActionPerformed
        tudoInvisivel();
        dispose();
        Tela4_emprestimo tela = new Tela4_emprestimo(lista);
        tela.setVisible(true);
    }//GEN-LAST:event_jTBemprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela5_listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela5_listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela5_listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela5_listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela5_listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrarAluno;
    private javax.swing.JButton jBcadastrarLivro;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsair1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBopcoes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPTalunos;
    private javax.swing.JPanel jPTdevolucoes;
    private javax.swing.JPanel jPTemprestimos;
    private javax.swing.JPanel jPTlivros;
    private javax.swing.JPanel jPlistar;
    private javax.swing.JPanel jPlistas;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPmenuCadastrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jTBbuscar;
    private javax.swing.JToggleButton jTBcadastrar;
    private javax.swing.JToggleButton jTBdevolucao;
    private javax.swing.JToggleButton jTBemprestimo;
    private javax.swing.JToggleButton jTBmulta;
    private javax.swing.JToggleButton jTBremover;
    private javax.swing.JTable jTlistaAlunos;
    private javax.swing.JTable jTlistaDevolucoes;
    private javax.swing.JTable jTlistaEmprestimos;
    private javax.swing.JTable jTlistaLivros;
    // End of variables declaration//GEN-END:variables

    public void tornarInvisivel() {
        jPTlivros.setVisible(false);
        jPTalunos.setVisible(false);
        jPTemprestimos.setVisible(false);
        jPTdevolucoes.setVisible(false);
    }
    
     private void tudoInvisivel() {
        jPmenuCadastrar.setVisible(false);
    }

    private void tornarGrid() {
        jPmenuCadastrar.setLayout(new GridLayout(2,1));
    }
}
